version: '3.8'

services:
  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.fastapi
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DATABASE_URL: ${DATABASE_URL:-postgresql://airflow:airflow@postgres/app}
      PYTHONPATH: /app/src
    volumes:
      - ./backend/src:/app/src
      - ./backend/requirements.txt:/app/requirements.txt
    networks:
      - app-network
    restart: unless-stopped
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  app-network:
    driver: bridge
